### ISSUE TITLE
HELP!!!!!!!!!

### ISSUE THREAD

**Issue by ak-47-brar** [Jigarvarma2005/TorrentWaver#1]
/workspaces/video-compressor/TorrentWaver/app.py:17: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been import
ed may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util (/home/codespace/.local/lib/python3.10/site-packages/urllib3/util/__init__.py)', 'urllib3.util.ssl_ (/home/codespace/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py)', 'aiohttp.client_reqrep (/home/codespace/.python/current/lib/python3.10/site-packages/aiohttp/client_reqrep.py)', 'aiohttp.client (/home/codespace/.python/current/lib/python3.10/site-packages/aiohttp/client.py)', 'aiohttp.connector (/home/codespace/.python/current/lib/python3.10/site-packages/aiohttp/connector.py)', 'aiohttp.client_exceptions (/home/codespace/.python/current/lib/python3.10/site-packages/aiohttp/client_exceptions.py)'].                                                                                                                               monkey.patch_all()
Server initialized for gevent.
Traceback (most recent call last):
  File "/workspaces/video-compressor/TorrentWaver/app.py", line 54, in <module>
    aria2 = aria_start()
  File "/workspaces/video-compressor/TorrentWaver/app.py", line 48, in aria_start
    process = subprocess_run(cmd)
  File "/workspaces/video-compressor/TorrentWaver/app.py", line 24, in subprocess_run
    subproc = Popen(cmd, stdout=PIPE, stderr=PIPE, shell=True, universal_newlines=True)
  File "/home/codespace/.python/current/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/codespace/.python/current/lib/python3.10/subprocess.py", line 1775, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
AttributeError: 'NoneType' object has no attribute 'fork_exec'

**Comment by jigarvarma2k20** [comment]
can try the latest changes?
